language: rust

services:
  - redis-server

rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo update
  - cargo check --all 
  - cargo test --all-features --all
  
after_success:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
          cargo install cargo-tarpaulin
          echo "Uploaded code coverage"
          cargo tarpaulin --out Xml --all --all-features --ignore-tests --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
      fi
