[package]
name = "hitbox-redis"
version = "0.1.0"
authors = ["Belousow Makc <lib.bmw@gmail.com>", "Andrey Ermilov <andrerm@ya.ru>"]
edition = "2018"
description = "hitbox redis backend actor."
license-file = "LICENSE"
workspace = ".."

[dependencies]
hitbox-backend = { path = "../hitbox-backend" }
actix = "0.11"
log = "0.4"
redis = { version = "0.20", features = ["tokio-comp", "connection-manager"] }
actix_derive = "0.6"
actix-rt = "2"
thiserror = "1"

[dev-dependencies]
tokio = { version = "1", features = ["time"] }
