[package]
name = "hitbox-redis"
version = "0.1.0"
authors = ["Belousow Makc <lib.bmw@gmail.com>", "Andrey Ermilov <andrerm@ya.ru>"]
license = "MIT"
edition = "2018"
description = "Hitbox redis backend actor."
readme = "README.md"
repository = "https://github.com/hit-box/hitbox/"
categories = ["caching", "asynchronous"]
keywords = ["cache", "actix", "async", "cache-backend", "hitbox"]

[dependencies]
hitbox-backend = { path = "../hitbox-backend", version = "0.1" }
actix = "0.10"
log = "0.4"
redis = { version = "0.17", features = ["tokio-rt-core", "connection-manager"] }
actix_derive = "0.5"
thiserror = "1"

[dev-dependencies]
actix-rt = { version = "1.1" }
tokio = { version = "0.2", features = ["time"] }
