[package]
name = "hitbox"
version = "0.0.1"
authors = ["Belousow Makc <lib.bmw@gmail.com>", "Andrey Ermilov <andrerm@ya.ru>"]
edition = "2018"
description = "Rust cache system."
license-file = "LICENSE"

[dependencies]
actix = "0.11"
actix-rt = "2"
hitbox-backend = { path = "../hitbox-backend" }
hitbox-derive = { path = "../hitbox-derive", optional = true }
serde_json = "1"
serde_qs = { version = "0.8", optional = true }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
prometheus = { version = "0.12", optional = true }
lazy_static = { version = "1", optional = true }
tracing = "0.1"

[dev-dependencies]
env_logger = "0.8"
actix_derive = "0.6"
actix-web = "3"

[features]
default = []

derive = ["hitbox-derive", "serde_qs"]
metrics = ["prometheus", "lazy_static"]
