[package]
name = "hitbox-examples"
version = "0.0.0"
publish = false
edition = "2018"

[features]
default = []

[dev-dependencies]
hitbox-actix = { path = "../hitbox-actix", features = ["redis"]}
actix = "0.10"
log = "0.4"
actix-rt = "1"
serde_json = "1"
serde_qs = { version = "0.7" }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
prometheus = { version = "0.10" }
env_logger = "0.8"
actix_derive = "0.5"
actix-web = "3"
