[package]
name = "hitbox-examples"
version = "0.0.0"
publish = false
edition = "2018"

[features]
default = []

[dev-dependencies]

hitbox = { path = "../hitbox" }
hitbox-redis = { path = "../hitbox-redis" }
hitbox-derive = { path = "../hitbox-derive" }
