[package]
name = "hitbox-examples"
version = "0.0.0"
publish = false
edition = "2018"

[features]
default = []

[dev-dependencies]
hitbox = { path = "../hitbox", features = ["derive"] }
hitbox-actix = { path = "../hitbox-actix", features = ["redis"] }
actix = "0.10"
log = "0.4"
actix-rt = "1.1"
tokio = { version = "0.2", features = ["time"] }
serde_json = "1"
serde_qs = { version = "0.8" }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
prometheus = { version = "0.12" }
env_logger = "0.8"
actix_derive = "0.5"
actix-web = "3"
tracing = "0.1"
tracing-subscriber = "0.2"
